/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ssnfs.h"
#include <string.h>
#include <memory.h>
/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

open_output *
open_file_1(argp, clnt)
	open_input *argp;
	CLIENT *clnt;
{
	static open_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, open_file,
        (xdrproc_t)xdr_open_input, (caddr_t)argp,
        (xdrproc_t)xdr_open_output, (caddr_t)&clnt_res,
        TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

read_output *
read_file_1(argp, clnt)
	read_input *argp;
	CLIENT *clnt;
{
	static read_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, read_file,
              (xdrproc_t)xdr_read_input, (caddr_t)argp,
              (xdrproc_t)xdr_read_output, (caddr_t)&clnt_res,
              TIMEOUT) != RPC_SUCCESS)

		return (NULL);
	return (&clnt_res);
}

write_output *
write_file_1(argp, clnt)
	write_input *argp;
	CLIENT *clnt;
{
	static write_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, write_file,
              (xdrproc_t)xdr_write_input, (caddr_t)argp,
              (xdrproc_t)xdr_write_output, (caddr_t)&clnt_res,
              TIMEOUT) != RPC_SUCCESS)

		return (NULL);
	return (&clnt_res);
}

list_output *
list_files_1(argp, clnt)
	list_input *argp;
	CLIENT *clnt;
{
	static list_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, list_files,
              (xdrproc_t)xdr_list_input, (caddr_t)argp,
              (xdrproc_t)xdr_list_output, (caddr_t)&clnt_res,
              TIMEOUT) != RPC_SUCCESS)

		return (NULL);
	return (&clnt_res);
}

delete_output *
delete_file_1(argp, clnt)
	delete_input *argp;
	CLIENT *clnt;
{
	static delete_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, delete_file,
              (xdrproc_t)xdr_delete_input, (caddr_t)argp,
              (xdrproc_t)xdr_delete_output, (caddr_t)&clnt_res,
              TIMEOUT) != RPC_SUCCESS)

		return (NULL);
	return (&clnt_res);
}

close_output *
close_file_1(argp, clnt)
	close_input *argp;
	CLIENT *clnt;
{
	static close_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, close_file,
              (xdrproc_t)xdr_close_input, (caddr_t)argp,
              (xdrproc_t)xdr_close_output, (caddr_t)&clnt_res,
              TIMEOUT) != RPC_SUCCESS)

		return (NULL);
	return (&clnt_res);
}

seek_output *
seek_position_1(argp, clnt)
	seek_input *argp;
	CLIENT *clnt;
{
	static seek_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, seek_position,
              (xdrproc_t)xdr_seek_input, (caddr_t)argp,
              (xdrproc_t)xdr_seek_output, (caddr_t)&clnt_res,
              TIMEOUT) != RPC_SUCCESS)

		return (NULL);
	return (&clnt_res);
}

create_output *
create_file_1(argp, clnt)
	create_input *argp;
	CLIENT *clnt;
{
	static create_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, create_file,
              (xdrproc_t)xdr_create_input, (caddr_t)argp,
              (xdrproc_t)xdr_create_output, (caddr_t)&clnt_res,
              TIMEOUT) != RPC_SUCCESS)

		return (NULL);
	return (&clnt_res);
}
